// 📄 ไฟล์ employees.js (เวอร์ชันตรวจสอบและแก้ไขตามไฟล์สถิติจริงของบริษัท)
const excelEmployees = [
    { id: "1001", firstName: "มณเทียน", lastName: "ทองมนต์", department: "คลังสินค้าและขนส่ง" },
    { id: "1002", firstName: "มาลัย", lastName: "สุยะตุ่น", department: "คลังสินค้าและขนส่ง" },
    { id: "1003", firstName: "ชูศักดิ์", lastName: "สุยะตุ่น", department: "คลังสินค้าและขนส่ง" },
    { id: "1004", firstName: "ครองทรัพย์", lastName: "นามแสน", department: "คลังสินค้าและขนส่ง" },
    { id: "1005", firstName: "สุชาติ", lastName: "นนทฤทธิ์", department: "คลังสินค้าและขนส่ง" },
    { id: "1006", firstName: "อลงกรณ์", lastName: "ผูกพานิช", department: "คลังสินค้าและขนส่ง" },
    { id: "1007", firstName: "ณิชนันทน์", lastName: "เอื้อเวชนิชกุล", department: "ขายและการตลาด" },
    { id: "1008", firstName: "วันเฉลิม", lastName: "พุ่มจันทร์", department: "คลังสินค้าและขนส่ง" },
    { id: "1009", firstName: "สุชาติ", lastName: "นนทฤทธิ์", department: "บัญชีและการเงิน" }, // (หมายเหตุ: มีชื่อ-สกุลนี้ในแผนกบัญชีด้วย)
    { id: "1010", firstName: "พิรุณ", lastName: "ระตาพลอย", department: "คลังสินค้าและขนส่ง" },
    { id: "1011", firstName: "วศิน", lastName: "เกตุหอม", department: "คลังสินค้าและขนส่ง" },
    { id: "1012", firstName: "อินทุอร", lastName: "ลีระพานิช", department: "จัดซื้อ" },
    { id: "1013", firstName: "เรืองยศ", lastName: "เพ็งชะตา", department: "คลังสินค้าและขนส่ง" },
    { id: "1014", firstName: "สิริเชษฐ์", lastName: "ไผ่เพชร", department: "คลังสินค้าและขนส่ง" },
    { id: "1015", firstName: "ญาติกา", lastName: "พงษ์สินมณี", department: "ขายและการตลาด" },
    { id: "1018", firstName: "รุ่งทิวา", lastName: "สิงห์พันธ์", department: "ขายและการตลาด" },
    { id: "1019", firstName: "ธนษา", lastName: "ธารารัตนภูดล", department: "QMR/DCC/QC" },
    { id: "1025", firstName: "อินทุอร", lastName: "ลีระพานิช", department: "บัญชีและการเงิน" },
    { id: "1031", firstName: "เบญจมาศ", lastName: "ประยูรวงษ์", department: "บัญชีและการเงิน" },
    { id: "1033", firstName: "ชฎาพร", lastName: "วรรณเกษม", department: "ขายและการตลาด" },
    { id: "1035", firstName: "แสงสุลี", lastName: "โพยนอก", department: "คลังสินค้าและขนส่ง" },
    { id: "1040", firstName: "ชัย", lastName: "สิทธิศร", department: "คลังสินค้าและขนส่ง" },
    { id: "1041", firstName: "สิรัญญา", lastName: "นัดดา", department: "ขายและการตลาด" },
    { id: "1043", firstName: "เมธาวี", lastName: "สมบัติ", department: "ขายและการตลาด" },
    { id: "1045", firstName: "ชฎาพร", lastName: "วรรณเกษม", department: "คลังสินค้าและขนส่ง" },
    { id: "1050", firstName: "เมธาวี", lastName: "สมบัติ", department: "ขายและการตลาด" }, // (หมายเหตุ: ตรวจสอบพบชื่อซ้ำหรือแยกบทบาท)
    { id: "1053", firstName: "ณัฐกฤตา", lastName: "คำวงษ์", department: "ขายและการตลาด" },
    { id: "1055", firstName: "สงัด", lastName: "โสตาราช", department: "คลังสินค้าและขนส่ง" },
    { id: "1058", firstName: "ธัญพร", lastName: "ศรีพิสุทธิ์", department: "QMR/DCC/QC" },
    { id: "1060", firstName: "ชินาภา", lastName: "จันทวงศ์", department: "QMR/DCC/QC" },
    { id: "1063", firstName: "แพรวพรรณ", lastName: "มีคำ", department: "ขายและการตลาด" },
    { id: "1065", firstName: "นันธญา", lastName: "สุขเพ็ง", department: "เลขาผู้บริหาร" },
    { id: "1070", firstName: "ยงยุทธ", lastName: "ศักดารัตน์", department: "จัดซื้อ" },
    { id: "1075", firstName: "ทักษ์ดนัย", lastName: "สารวัน", department: "คลังสินค้าและขนส่ง" },
    { id: "1076", firstName: "กิ่งแก้ว", lastName: "ฟ้องเสียง", department: "ขายและการตลาด" },
    { id: "1080", firstName: "ชลลดา", lastName: "สุวรรณทิพย์", department: "ขายและการตลาด" },
    { id: "1084", firstName: "มินธาดา", lastName: "สามิน", department: "คลังสินค้าและขนส่ง" },
    { id: "1085", firstName: "เลา", lastName: "นามแสน", department: "ขายและการตลาด" },
    { id: "1087", firstName: "จีรนันท์", lastName: "โคตมณี", department: "ขายและการตลาด" },
    { id: "1088", firstName: "วิทยา", lastName: "ปักษาสุข", department: "QMR/DCC/QC" },
    { id: "1090", firstName: "ปิยณัฐ", lastName: "มีรอด", department: "คลังสินค้าและขนส่ง" },
    { id: "1094", firstName: "จีรนันท์", lastName: "กรณ์จิราลักษณ์", department: "จัดซื้อ" },
    { id: "1095", firstName: "กรรณิกา", lastName: "บุญโพธิ์กอง", department: "ขายและการตลาด" },
    { id: "1100", firstName: "พรรณธิภา", lastName: "เสาร์สูงยาง", department: "คลังสินค้าและขนส่ง" },
    { id: "1102", firstName: "ณิชาภา", lastName: "เหลียวดูดี", department: "จัดซื้อ" },
    { id: "1105", firstName: "ดนุสรณ์", lastName: "ระวังชนม์", department: "คลังสินค้าและขนส่ง" },
    { id: "1107", firstName: "พรกนก", lastName: "สายเปา", department: "บัญชีและการเงิน" },
    { id: "1108", firstName: "Khin Naing", lastName: "Htwe", department: "คลังสินค้าและขนส่ง" },
    { id: "1109", firstName: "สุภาวดี", lastName: "จ้างไธสง", department: "บัญชีและการเงิน" },
    { id: "1110", firstName: "ดนุสรณ์", lastName: "ระวังชนม์", department: "คลังสินค้าและขนส่ง" },
    { id: "1112", firstName: "นฤมล", lastName: "หมื่นสุนทร", department: "บัญชีและการเงิน" },
    { id: "1113", firstName: "Thu", lastName: "Htay", department: "คลังสินค้าและขนส่ง" },
    { id: "1114", firstName: "เมธินี", lastName: "โหมดเถื่อน", department: "บัญชีและการเงิน" },
    { id: "1115", firstName: "เมธินี", lastName: "โหมดเถื่อน", department: "คลังสินค้าและขนส่ง" },
    { id: "1116", firstName: "ปิยธิดา", lastName: "ตันลือนาม", department: "ขายและการตลาด" },
    { id: "1125", firstName: "ศดานันท์", lastName: "จินดา", department: "QMR/DCC/QC" }, // (หมายเหตุ: สถานะในไฟล์คือลาออกระหว่างปี)
    { id: "1127", firstName: "ทักษ์ดนัย", lastName: "สารวัน", department: "ขายและการตลาด" },
    { id: "1128", firstName: "ปริศนา", lastName: "ท่าไว", department: "บุคคลและความปลอดภัย" },
    { id: "1138", firstName: "วิศรุต", lastName: "พิมเพราะ", department: "ขายและการตลาด" },
    { id: "1139", firstName: "ศศิภา", lastName: "แตงโช", department: "จัดซื้อ" },
    { id: "1140", firstName: "รุ่งเกียรติ", lastName: "สิงห์พันธ์", department: "ขายและการตลาด" },
    { id: "1142", firstName: "รัชนี", lastName: "รัตนชัยสิทธิกุล", department: "บุคคลและความปลอดภัย" },
    { id: "1143", firstName: "ปุญญาภา", lastName: "สร้อยทอง", department: "QMR/DCC/QC" },
    { id: "1144", firstName: "ธนกฤต", lastName: "อิทธิยะ", department: "QMR/DCC/QC" },
    { id: "1146", firstName: "สุวดี", lastName: "ตุ้มเพ็ชร", department: "จัดซื้อ" }
];
