// 📄 ไฟล์ employees.js (เวอร์ชันอัปเดตพนักงานทุกคนครบถ้วน)
const excelEmployees = [
    { id: "1001", firstName: "มณเทียน", lastName: "ทองมนต์", department: "คลังสินค้าและขนส่ง" },
    { id: "1002", firstName: "มาลัย", lastName: "สุยะตุ่น", department: "คลังสินค้าและขนส่ง" },
    { id: "1003", firstName: "ชูศักดิ์", lastName: "สุยะตุ่น", department: "คลังสินค้าและขนส่ง" },
    { id: "1004", firstName: "ครองทรัพย์", lastName: "นามแสน", department: "คลังสินค้าและขนส่ง" },
    { id: "1065", firstName: "นันธญา", lastName: "สุขเพ็ง", department: "เลขาผู้บริหาร" },
    { id: "1084", firstName: "มินธาดา", lastName: "สามิน", department: "คลังสินค้าและขนส่ง" },
    { id: "1087", firstName: "จีรนันท์", lastName: "โคตมณี", department: "ขายและการตลาด" },
    { id: "1128", firstName: "ปริศนา", lastName: "ท่าไว", department: "บุคคลและความปลอดภัย" },
    { id: "1142", firstName: "รัชนี", lastName: "รัตนชัยสิทธิกุล", department: "บุคคลและความปลอดภัย" },
    { id: "1015", firstName: "ณิชนันทน์", lastName: "เอื้อเวชนิชกุล", department: "ขายและการตลาด" },
    { id: "1020", firstName: "ญาติกา", lastName: "พงษ์สินมณี", department: "ขายและการตลาด" },
    { id: "1025", firstName: "อินทุอร", lastName: "ลีระพานิช", department: "บัญชีและการเงิน" },
    { id: "1030", firstName: "ธนษา", lastName: "ธารารัตนภูดล", department: "บัญชีและการเงิน" },
    { id: "1035", firstName: "แสงสุลี", lastName: "โพยนอก", department: "คลังสินค้าและขนส่ง" },
    { id: "1040", firstName: "ชัย", lastName: "สิทธิศร", department: "คลังสินค้าและขนส่ง" },
    { id: "1045", firstName: "ชฎาพร", lastName: "วรรณเกษม", department: "คลังสินค้าและขนส่ง" },
    { id: "1050", firstName: "เมธาวี", lastName: "สมบัติ", department: "ขายและการตลาด" },
    { id: "1055", firstName: "สงัด", lastName: "โสตาราช", department: "คลังสินค้าและขนส่ง" },
    { id: "1070", firstName: "ศดานันท์", lastName: "จินดา", department: "บัญชีและการเงิน" },
    { id: "1075", firstName: "ทักษ์ดนัย", lastName: "สารวัน", department: "คลังสินค้าและขนส่ง" },
    { id: "1090", firstName: "ปิยณัฐ", lastName: "มีรอด", department: "คลังสินค้าและขนส่ง" },
    { id: "1095", firstName: "อนุรักษ์", lastName: "เหมือนแก้ว", department: "จัดซื้อ" },
    { id: "1100", firstName: "พรรณธิภา", lastName: "เสาร์สูงยาง", department: "คลังสินค้าและขนส่ง" },
    { id: "1105", firstName: "ณิชาภา", lastName: "เหลียวดูดี", department: "จัดซื้อ" },
    { id: "1110", firstName: "ดนุสรณ์", lastName: "ระวังชนม์", department: "คลังสินค้าและขนส่ง" },
    { id: "1115", firstName: "เมธินี", lastName: "โหมดเถื่อน", department: "คลังสินค้าและขนส่ง" },
    { id: "1201", firstName: "Thu Htay", lastName: "", department: "คลังสินค้าและขนส่ง" }
];